### ISSUE TITLE
Support sorting of records

### ISSUE THREAD

**Issue by gmanriqueUy** [mswjs/data#102]
First of all, thanks for this library! It really eases the process of mocking a database.

While implementing pagination in my mock REST API, I couldn't find any documentation about sorting. Does that feature exists and is not documented? If not, are there any plans to add it already or I'm the first one with a use case for it?

Thanks in advance!

**Comment by kettanaito** [comment]
Hey, @gmanriqueUy. Thank you for the kind words.

Currently, there is no sorting support when paginating entities. How do you see such API being used?

I can imagine something like this:

```js
db.user.findMany({
  where: {
    country: {
      equals: 'Spain'
    }
  },
  orderBy: [
    {
      firstName: 'asc'
    },
    {
      role: 'desc'
    }
  ],
})
```

I wonder how we can approach sorting of the nested properties with such API. For example, in the ordered list above, sort all `user.posts` by title.

**Comment by kettanaito** [comment]
The `orderBy` option is now supported in [0.5.0](https://github.com/mswjs/data/releases/tag/v0.5.0).
