### ISSUE TITLE
comparatorFn is not a function - updateMany doesn't support 'where', expects 'which' v0.5.0

### ISSUE THREAD

**Issue by VickyKoblinski** [mswjs/data#111]
Hey, I see that recently `which` was replaced with `where`. I have the latest version of this mswjs/data (v0.5.0) from npm and when I try using `where` in `updateMany` I get:

````
TypeError: comparatorFn is not a function
````

Changing `where` to `which` has resolved my problem for now :)

**Comment by kettanaito** [comment]
Hey, @VickyKoblinski. 

Could you please share your `updateMany` call? The error you're describing hints that there's an invalid comparator being used (equals/gte/lt/etc.). If you share your usage I can try to help you solve the problem.

**Comment by kettanaito** [comment]
I confirm that version `0.5.0` expects and properly handles the `where` property in all model operations. 

Here's an integration test for the `updateMany` method that uses `where` and successfully passes:
https://github.com/mswjs/data/blob/808295f6bb4a26f82a4085da9165da3bf4ac585c/test/model/updateMany.test.ts#L27-L41

Please ensure you're using the latest `@mswjs/data` version. You can do so by:

```sh
$ npm ls @mswjs/data
```
Or just update to the latest published version by:

```sh
$ npm install @mswjs/data@latest -D
# or
$ yarn add @mswjs/data@latest
```
