### ISSUE TITLE
add req.query support

### ISSUE THREAD

**Issue by zkindest** [mswjs/data#123]
GET /api/replies/test?thread_id=123

```
req.query is undefined
```
and also typescript issue
```ts
Property 'query' does not exist on type 'RestRequest<DefaultRequestBody, RequestParams>'
```

**Comment by kettanaito** [comment]
Hey, @zkindest.

MSW does not have a custom `query` property on the request object. Instead, we use the standard URLSearchParams under `req.url.searchParams`. **Learn more about [working with query parameters](https://mswjs.io/docs/recipes/query-parameters)**.

In your example, accessing the query parameters would look like this:

```js
const threadId = req.url.searchParams.get('thread_id')
```
