### ISSUE TITLE
Support global "reset" capability

### ISSUE THREAD

**Issue by kentcdodds** [mswjs/data#134]
I want to keep all my tests completely isolated. This means I need the ability to drop all values in every database:

```ts
import {dropAll} from '@mswjs/data'

afterEach(() => dropAll())
```

I would use that in my global test configuration so every test could be completely isolated.

**Comment by kettanaito** [comment]
If you're using a single database in a single test file and wish for the tests to start from the clean state of the database, use `drop`.

```js
// my.test.js
import { factory, drop } from '@mswjs/data'

const db = factory({ ... })

afterEach(() => {
  drop(db)
})

test('one', () => {
  db.user.create({ firstName: 'John' })
})

test('two', () => {
  db.user.findFirst({ where: { firstName: { equals: 'John' } } })
  // null, no user has been created in this test.
})
```
