### ISSUE TITLE
Fields with type `Array` cannot be an array of object

### ISSUE THREAD

**Issue by nvh95** [mswjs/data#165]
I have example code here:
https://github.com/nvh95/msw-example/blob/d144e5c98f165c15b8758e1157fa478952307d7f/src/mocks/browser.js#L4-L29
Given I have this schema:
```js
const db = factory({
  user: {
    id: primaryKey(Number),
    email: String,
    additional_data: Array,
  },
});
```
Basically, I have a field `additional_data` which is an `Array`. If I create array of primitive type like `string` or `number`, it works fine. 
```js
db.user.create({
  ...
  additional_data: [1, 2, 3 ],
});
```
![image](https://user-images.githubusercontent.com/8603085/142595383-c0eec79e-783b-4a6e-9d7d-0b848203f741.png)

But if `additional_data` is an array of object, `@mswjs/data` seems cannot process it and returns an empty array
```js
db.user.create({
  ...
  additional_data: [
    {
      key: "hobby",
      value: "code",
    },
    {
      key: "phone",
      value: "12345",
    },
  ],
});
```
![Screenshot 2021-11-19 at 15 50 10](https://user-images.githubusercontent.com/8603085/142594971-51e6ba0e-2ce7-418d-b319-43f829ab05ba.png)

I have code to reproduce this issue in https://github.com/nvh95/msw-example/blob/msw-example-2021.11.19
```bash
git clone git@github.com:nvh95/msw-example.git
git checkout msw-example-2021.11.19
npm i
npm start
```

@kettanaito Can you take a look? Is this an issue or I misuse `additional_data: Array` (I refer to #113). (definitely I don't want to use `manyOf` here). Thank you very much.

**Comment by VanTanev** [comment]
@kettanaito I want to second this, I consider this a valid use.

The change was introduced in here: https://github.com/mswjs/data/pull/143/files#diff-64401d98a99c109c65a62a9cc791a32f21dddb5d08bce553aaa559b6aa0e382dL67-L74
And:
https://github.com/mswjs/data/blob/0970e7ed5a9094d6618ed6563f8bb3a00d5c9ecc/src/utils/isModelValueType.ts#L15

Previously, the check was just that we got an array, and the contents of this array did not matter, but now `create()` will drop any array that contains non-primitive values and replace it with an empty array.

I think this is a regression.

**Comment by kettanaito** [comment]
Hey, @nvh95. Thank you for reporting this.

This does look like an issue, as Data should support primitive arrays on model definitions. I'll take a look at the pull request opened by @roertbb (huge thanks 🙌 ) and see if it's indeed a regression.

**Comment by nvh95** [comment]
@kettanaito Thank you very much. I'm looking forward to see it fixed. In the mean time, I just want to share my work around:
1. Change the model:
```diff
const db = factory({
  user: {
    id: primaryKey(Number),
    email: String,
-    additional_data: Array,
+    additional_data: () => [
+      {
+        key: "hobby",
+        value: "code",
+      },
+      {
+       key: "phone",
+        value: "12345",
+      },
+    ],
+  },
});
```
2. Convert file contain the model from `.ts` to `.js`. Since TS does not allow us to define the model as above
![image](https://user-images.githubusercontent.com/8603085/143616331-2d8d506a-6fde-4163-872f-a61f27d10981.png)
Well, it looks not very good 🙈 but at least I feed some data for `msw` to respond.

**Comment by VanTanev** [comment]
The above workaround just gives a static value in the factory definition, you cannot create arrays with different values.
Here is a workaround that allows you to create different objects:
```ts

const db = factory({
  user: {
    id: primaryKey(Number),
    email: String,
    additional_data: Array,
  },
});

const user = {
  email: "example@example.com",
  additional_data: [
    {
      key: "hobby",
      value: "code",
    },
    {
      key: "phone",
      value: "12345",
    },
  ],  
}

// TEMPORARY WORKAROUND FOR #165
Object.defineProperty(user.additional_data, 'every', { value: () => true })

db.user.create(user)
```
