### ISSUE TITLE
Ability to store plain JSON as an attribute

### ISSUE THREAD

**Issue by ericchernuka** [mswjs/data#166]
Right now I have a data model that does not contain primary keys and is actually recursive. The backend actually stores the column a as JSON, but I'm currently having to build a model around it when it would be drastically simpler if I had the ability to have a dataType that was just a plain JSON object.

Example that I'm working with:
```
{
  type: "group",
  condition: "all",
  rules: [
    {
      type: "group",
      condition: "all",
      rules: [
        {
          type: "field",
          operator: "is",
          field: "a07eb0da-fe24-5dc8-93ef-511daa5a4fc7",
          value: "test"
        },
      ],
    },
  ],
}
```
All that being said, maybe there's an easier way to model this than what I'm thinking.

**Comment by ericchernuka** [comment]
Looks like https://github.com/mswjs/data/issues/165 may resolve my issues. 🤔

**Comment by kettanaito** [comment]
Hey, @ericchernuka. At the moment we don't support creation of static fixtures (data without primary keys). We've got the task opened and will schedule it for the future.
