### ISSUE TITLE
toHandlers method does not use the full baseUrl argument

### ISSUE THREAD

**Issue by oscles** [mswjs/data#224]
```javascript
//database.js
export const db = factory({
  banner: {
   ...
  },
  contact: {
   ....
  },
});

// server-handlers.js
import { db } from 'test/database.js;
const baseUrl = 'http://localhost:8000/api';

const bannerHandlers = db.banner.toHandlers('rest', urlApi);
const contactHandlers = db.contact.toHandlers('rest', urlApi);

export const handlers = [...bannerHandlers, ...contactHandlers];

// test-server.js
import { handlers } from './server-handlers';
import { setupServer } from 'msw/node';

const server = setupServer(...handlers);

export * from 'msw';
export { server };
```

Throw the following alert:
![image](https://user-images.githubusercontent.com/32989503/174221782-abc27908-c1d0-4f19-8538-b0005d064869.png)

This is the console output when printing `console.log(db.banner.toHandlers('rest', urlApi))`
![image](https://user-images.githubusercontent.com/32989503/174222253-920f1abd-0a48-4ede-be6a-ea2ba5982451.png)

does not add `api` segment to `baseUrl`

**Comment by kettanaito** [comment]
Hey, @oscles. 

You are missing a trailing slash in your base URL in order for it to be taken fully when composing request handlers URL. Compare:

```
// http://localhost:8000/user/:id
new URL('user/:id', 'http://localhost:8000/api')

// http://localhost:8000/api/user/:id
new URL('user/:id', 'http://localhost:8000/api/')
```
