### ISSUE TITLE
Feature Request: Delay for toHandlers

### ISSUE THREAD

**Issue by mwyrembl** [mswjs/data#227]
This is a feature request.

It would be helpful for local development and testing if the toHandlers method would support a delay parameter in milliseconds to delay the response.

Example for delaying the response for 2 seconds:

toHandlers("rest", "http://localhost:3000/api/", 2000);

**Comment by cp3hnu** [comment]
Maybe consider adding response transformers(https://mswjs.io/docs/basics/response-transformer)

**Comment by kettanaito** [comment]
I believe I've answered this in [this discussion](https://github.com/mswjs/data/discussions/223).

**Comment by cp3hnu** [comment]
My use case is that the actual network request response format is
`
{
  success: true,
  data: user,        // model
  message: "success"
}
`
In that case, toHandlers doesn't fit in.
