### ISSUE TITLE
"graphql": "^16.6.0",

### ISSUE THREAD

**Issue by oteoe** [mswjs/data#239]
msw/data has an issue with  "graphql": "^16.6.0", reverting to 15.5 fixes the issue.

msw v0.46.1 has graphql as dependency

https://github.com/mswjs/msw/commit/8436515fd93e3f372205815b52ffc3a572da2690

**Comment by kettanaito** [comment]
Hey, @oteoe.

Could you provide more details on which exact issue happens? A reproduction repository would be nice.
