### ISSUE TITLE
Consider renaming `which` to `where`

### ISSUE THREAD

**Issue by kimroen** [mswjs/data#65]
The property used to filter in mswjs/data is named `which`, citing [being heavily inspired by Prisma](https://twitter.com/ApiMocking/status/1381718391422132225). However, Prisma does not use `which`, it uses `where`:

https://www.prisma.io/docs/concepts/components/prisma-client/filtering-and-sorting

Is it possible that this is a mistake?

`where` is also the preferred word for other ORMs (presumably because the keyword is `WHERE` in SQL), such as:

- [Sequelize](https://sequelize.org/master/manual/model-querying-basics.html#applying-where-clauses)
- [TypeORM](https://typeorm.io/#/select-query-builder/what-is-querybuilder)
- [Firestore](https://firebase.google.com/docs/reference/js/firebase.firestore.Query#where)
- [Mirage](https://miragejs.com/api/classes/schema/#where)

Non-js:

- [SQLAlchemy (python)](https://docs.sqlalchemy.org/en/14/orm/queryguide.html#select-statements)
- [Rails' ActiveRecord](https://guides.rubyonrails.org/active_record_basics.html#read)
- [Ecto (elixir)](https://hexdocs.pm/ecto/Ecto.Query.html)

**Comment by kettanaito** [comment]
Thank you for reporting this, @kimroen. You're absolutely right, and the `which` choice is an oversight on my part (@msutkowski has also pointed this out). I think we should adopt `where` instead.

Please, would you be interested in shipping this change?

**Comment by kimroen** [comment]
Wonderful 👍 🎉
