### ISSUE TITLE
`primaryKey` types does not support numbers

### ISSUE THREAD

**Issue by cloud-walker** [mswjs/data#82]
Hello! I'm trying out the package for the first time, and I've noticed that the primaryKey type does not support numbers:

https://github.com/mswjs/data/blob/8bb7419689dcbea52f5b758d4a302ab06e9310eb/src/glossary.ts#L8

It is intentional? I need it to be number, as the real db my backend is using has numeric ids 😅 

I'll be happy to open a PR if needed ❤️

**Comment by marcosvega91** [comment]
Hi @cloud-walker thanks for opening the issue :).

I think that there is an issue there. [here](https://github.com/mswjs/data/blob/8bb7419689dcbea52f5b758d4a302ab06e9310eb/src/glossary.ts#L18-L20) I guess `getValue` should return a type `KeyType` instead of `PrimaryKeyType`. An help will be great 🥳

**Comment by kettanaito** [comment]
Or we'd rather extend `PrimaryKeyType` to include a `number` and be a union type. I think `KeyType` represents an internal key for the model in a database, not the public primary key type.

**Comment by cloud-walker** [comment]
I was thinking the same thing, I will open a PR and we will continue the discussion there
