### ISSUE TITLE
Model doesn't support array of strings, numbers or booleans

### ISSUE THREAD

**Issue by juusot** [mswjs/data#97]
Hi.

I cannot create models with array fields. The models support array of arrays or array of object, **but not array of strings, numbers or booleans**.

Here is an example:
```
import { primaryKey } from "@mswjs/data";

const car = {
  id: primaryKey((id: string) => id),
  name: (carName: string): string => carName,
  dimensions: () => [1, 2, 3], // <-- error
};
```

The browser gives the following error:
```
main.js:27438 Uncaught TypeError: Cannot use 'in' operator to search for '__type' in true
    at Object.isInternalEntity (isInternalEntity.js?0caa:9)
    at eval (removeInternalProperties.js?5ec5:44)
    at Array.map (<anonymous>)
    at eval (removeInternalProperties.js?5ec5:43)
    at Array.map (<anonymous>)
    at Object.removeInternalProperties (removeInternalProperties.js?5ec5:35)
    at Object.create (factory.js?898e:72)
    at handlers (person.mockRequest.ts?f8cc:34)
    at eval (handlers.ts?0e5c:21)
    at Array.flatMap (<anonymous>)
```

Am I doing something wrong or is this a bug?

Thanks!

**Comment by kettanaito** [comment]
Hey, @juusot. Thanks for reporting this.

Array values are currently only supported through the `manyOf` relation. Using it, you represent an Array of _objects_ (models):

```js
import { factory, primaryKey } from '@mswjs/data'

factory({
  user: {
    id: primaryKey(ID),
    posts: manyOf('post')
  },
  post: {
    id: primaryKey(ID)
  }
})
```

With this factory, `user.posts` is an Array of `post` entities. 

We'd like to have support for primitive types, as strings/numbers/booleans as well, but it's not implemented at the moment. If you're interested at tackling this, we'd love your assistance and will help you with the code review.
